Use stack2cabal to configure cabal.project
https://www.stackage.org/lts-21.6/cabal.config now contains the
constraint `haskeline installed`. GHC 9.4.5 comes with haskeline 0.8.2
preinstalled but our configuration contains the
source-repository-package for haskeline 0.8.2.1 so if you try to run
`cabal build` you get the following conflict:

```
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] next goal: haskeline (user goal)
[__0] rejecting: haskeline-0.8.2.1 (constraint from project config
https://www.stackage.org/lts-21.6/cabal.config requires installed instance)
[__0] rejecting: haskeline-0.8.2/installed-0.8.2, haskeline-0.8.2,
haskeline-0.8.1.3, haskeline-0.8.1.2, haskeline-0.8.1.1, haskeline-0.8.1.0,
haskeline-0.8.0.1, haskeline-0.8.0.0, haskeline-0.7.5.0, haskeline-0.7.4.3,
haskeline-0.7.4.2, haskeline-0.7.4.1, haskeline-0.7.4.0, haskeline-0.7.3.1,
haskeline-0.7.3.0, haskeline-0.7.2.3, haskeline-0.7.2.2, haskeline-0.7.2.1,
haskeline-0.7.2.0, haskeline-0.7.1.3, haskeline-0.7.1.2, haskeline-0.7.1.1,
haskeline-0.7.1.0, haskeline-0.7.0.3, haskeline-0.7.0.2, haskeline-0.7.0.1,
haskeline-0.7.0.0, haskeline-0.6.4.7, haskeline-0.6.4.6, haskeline-0.6.4.5,
haskeline-0.6.4.4, haskeline-0.6.4.3, haskeline-0.6.4.2, haskeline-0.6.4.1,
haskeline-0.6.4.0, haskeline-0.6.3.2, haskeline-0.6.3.1, haskeline-0.6.3,
haskeline-0.6.2.4, haskeline-0.6.2.3, haskeline-0.6.2.2, haskeline-0.6.2.1,
haskeline-0.6.2, haskeline-0.6.1.6, haskeline-0.6.1.5, haskeline-0.6.1.3,
haskeline-0.6.1.2, haskeline-0.6.1.1, haskeline-0.6.1, haskeline-0.6.0.1,
haskeline-0.6, haskeline-0.5.0.1, haskeline-0.5, haskeline-0.4,
haskeline-0.3.2, haskeline-0.3.1, haskeline-0.3, haskeline-0.2.1,
haskeline-0.2 (constraint from user target requires ==0.8.2.1)
[__0] fail (backjumping, conflict set: haskeline)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: haskeline
```

Constraints from cabal imports cannot yet be overridden so it's not
possible to get rid of this conflict.

To work around this we instead use stack2cabal to generate a
cabal.project.freeze file for dependencies. This uses
https://www.stackage.org/lts-21.6/cabal.config at generation time to fix
the dependency versions